const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const equalsButton = document.querySelector('[data-equals]')
const allClearButton = document.querySelectorAll('[data-all-clear]')
const deleteButton = document.querySelectorAll('[data-delete]')
const operationButtons = document.querySelectorAll('[data-operation]')